### ISSUE TITLE
[BUG] Compile to Java / JS from ecore File doesn't work

### ISSUE THREAD

**Issue by electricalwind** [kevoree-modeling/idea-plugin#2]
When trying to use compile to JS or to Java function on an ecore file, the only effect is to create again a gen folder with two subfolder(Java and JS) erasing all previous generated file in these folder. The 2 subfolder are then left empty.
- KMF version: 4.5.0
- KMF Idea Plugin version: 15

**Comment by dukeboard** [comment]
I didn't reproduce this bug, can you send me the complet IDEA project please ?

**Comment by dukeboard** [comment]
Fixed in v16
